### ISSUE TITLE
need curvature for /y

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#114]
The thin diagonal on the /y needs curvature, in both the Light masters and the Contrast masters.

**Comment by kateliev** [comment]
Done. Please the /y owner to review and further tweak the design.

Also I have spotted that the contrast in lower part of :Cnd master is way too obvious. 
![image](https://user-images.githubusercontent.com/10247582/64692078-e4cae680-d49c-11e9-9f21-d69a921346e9.png)

This is mainly because the optical compensation for that stroke tapering at the bottom. I would suggest either correcting the weight of the horizontal part, or fixing it like shown below:
![image](https://user-images.githubusercontent.com/10247582/64692171-222f7400-d49d-11e9-8f64-f7454cb76ba7.png)
![image](https://user-images.githubusercontent.com/10247582/64692264-55720300-d49d-11e9-8896-e1a27a82299c.png)

**Comment by servantb** [comment]
Looks great. I've taken care of the contrast problem on the :Cnd.
Thanks.
