### ISSUE TITLE
Odd diffs in heights of small .dnom numerals

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#153]
OK, so _some_ of this could be put down to differences in overshoot. But the top of /five.dnom shouldn't vary at all from master to master, should it? So a difference of 20 units is surprising and probably not OK.

HEIGHT DIFFS 

/zero
:Lt 785
:Medium 784
:Blk 776
:LtCnd 781
:Cnd 781
:BlkCnd 774
:LtExp 785
:Exp 784
:BlkExp 776
:LtCtr 785
:Ctr 776
:BlkCtr 778

/five

:Lt 784
:Medium 773
:Blk 769
:LtCnd 779
:Cnd 768
:BlkCnd 764
:LtExp 784
:Exp 773
:BlkExp 769
:LtCtr 785
:Ctr 776
:BlkCtr 778

**Comment by kateliev** [comment]
Mostly due to an-isotropic interpolation. Nevertheless i have set a fixed height of 784 u for all masters + 10 u max overshoot to where it is needed. Have fixed /zero.onum for you to look at.

I would have fixed all of the .dnoms but then i realized that the figures are not yer ready so it is pretty pointless to work on them at this point. Hope @servantb finished the figures soon!

**Comment by tphinney** [comment]
@kateliev I understand that the numerals are ready to go now. /two was the last one, and it's done.

**Comment by kateliev** [comment]
Done:  /zero.dnom.new /one.dnom.new /two.dnom.new /three.dnom.new /four.dnom.new /five.dnom.new /six.dnom.new /seven.dnom.new /eight.dnom.new /nine.dnom.new It is all in your hands now!
