### ISSUE TITLE
Revise math characters contrast approach

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#166]
@servantb has proposed that we change the approach to the YOPQ axis (contrast) for math characters.

I have to agree that the high-contrast masters get awfully wonky.

He suggests that for the high-contrast masters: “I would say keep them the thickness of their non-contrast counterparts. The other option is to make them all the same as the :LtEtc masters.”

Let's call those options 1 and 2.

3) I am thinking an option would be in between both of those, perhaps taking the average of the normal weight and the :Lt weight, in both X and Y. That will at least give the “same” overall average weight as the contrast masters, albeit without contrast.

Comments welcome

**Comment by kateliev** [comment]
They should have no contrast whatsoever. So contrasts have to be equal to their non-contrast counterparts, but only in logic. So i would go with the following rules:
- all math symbols would have very low contrast across all masters
- all math symbols on non contrast masters might have a weight grading (from :Lt to :Blk), but the maximum stroke weight at :Blacks should be less (better) or equal to the lightest stroke of the weight. Meaning  that in the following situation I would go with 332 u (horizontal of /three) 
![image](https://user-images.githubusercontent.com/10247582/67073568-0dc35300-f190-11e9-985e-91a7ebe442f8.png)
- all math symbols of contrast masters will not have weight grading and maximum stroke weight should be that of the maximum of the minimum stroke weight. So that in the below example i would go with 36 u
![image](https://user-images.githubusercontent.com/10247582/67073859-a8bc2d00-f190-11e9-8b9a-823b76f93d07.png)

Thus:
- Non-contrasts:
![image](https://user-images.githubusercontent.com/10247582/67074013-f2a51300-f190-11e9-8c9e-2c6d73d56545.png)
![image](https://user-images.githubusercontent.com/10247582/67074208-4ca5d880-f191-11e9-9083-a5dd02d02d01.png)

- Contrasts:
![image](https://user-images.githubusercontent.com/10247582/67073949-d73a0800-f190-11e9-8e69-7e5070003825.png)
![image](https://user-images.githubusercontent.com/10247582/67074293-837bee80-f191-11e9-98dd-44c992491d31.png)

**Comment by kateliev** [comment]
Also i am kind of not found of this solution:
![image](https://user-images.githubusercontent.com/10247582/67074577-11f07000-f192-11e9-9ffd-7033d22509b0.png)

Same goes for /plusminus and other "compound" math glyphs. I would go either:
- hanging below baseline:
![image](https://user-images.githubusercontent.com/10247582/67074649-364c4c80-f192-11e9-98ec-42df785eaa4b.png)
- or change shape:
![image](https://user-images.githubusercontent.com/10247582/67074814-888d6d80-f192-11e9-9c81-fa190d4bac52.png)

**Comment by servantb** [comment]
Yes to what @tphinney said.

@kateliev, I agree that the current compound math glyph solution is less than ideal (as opposed to less than or equal to ideal 😉).

I think a better solution would be to tighten the angle of the comparative sign, and in the case of /plusminus, reduce the height of the plus.

<img width="714" alt="Screen Shot 2019-10-18 at 1 10 28 PM" src="https://user-images.githubusercontent.com/50463501/67125033-c5fcf580-f1a8-11e9-96a1-f1edf6647687.png">

**Comment by tphinney** [comment]
Note: affected glyphs are

/less
/greater
/greaterequal
/lessequal
/equal
/approxequal
/notequal
/logicalnot
/plus
/uni2212
/plusminus
/multiply
/divide
/uni2215
... and probably:
/uni27E8
/uni27E9

**Comment by kateliev** [comment]
Seems reasonable!

**Comment by tphinney** [comment]
1. For the compound math characters, I think @servantb 's solution above is good. Reduce the heights a bit, without changing shape or dropping below the baseline.
2. Regarding stroke thickness, let's go with @kateliev 's solution. After more review, I think it looks as good as what I was suggesting, maybe better. Plus, it is slightly less work, I think. Looks at least as good, less work = let’s do that.  ;)
3. The glyphs involved currently make a single contiguous block in the .enc file and the spreadsheet, _except_ the math mu (micro sign) which does not get revised. I will change the spreadsheet and .enc file to move it just before this set, just after the degree symbol.°

@kateliev Would you be willing to take on this set of changes, unless I get to this by the end of the weekend?

**Comment by kateliev** [comment]
I am ok with it! If you have not done them by Monday - I will!
