### ISSUE TITLE
Rebuild /ampersand.smcp

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#168]
A note so self, so i just do not forget @servantb request!

**Comment by tphinney** [comment]
Per @kateliev request, I added my additional-glyphs request to this issue.

I found that there are a few more glyphs for which it would be very handy to get a first-pass smcp version for, because they have some extra crossbar-type piece that would be handy to get scaled and positioned: Eth/Dcroat, Hbar, Lslash, Tbar

Afterwards, I can throw out the scaled letter and replace it with the already-cleaned-up .smcp version—butwant all those newly scaled crossbars! If needed I can later even make the crossbar a separate glyph so that we get the desired component/.UFO/VF export behavior....

**Comment by kateliev** [comment]
Done! /ampersand.smcp.new /Eth.smcp.new /Hbar.smcp.new /Lslash.smcp.new /Tbar.smcp.new
