### ISSUE TITLE
Is /o.smcp too heavy, esp. in :BlkEtc ?

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#175]
Looking for more opinions on this. 

Maybe some others are too light, but seems like /o.smcp is just a bit heavy as well?

**Comment by kateliev** [comment]
Done! There is /o.smcp.light that is up my taste :) ... but

The problem is more complex than you imagine - Numerically the /o.smcp is up to the measurments of the whole set - so there is NO Bug - or looking at another angle - the whole set is a bug. Yes it is very heavy - mainly due to overly thick horizontals, that measure 430u but would looked so much better if they were 400 (406u as measured 90% of /p.smcp - the relation we see in UC, but that is another story). So yes it is black, but also /h.smcp has an overly black horizontal ... so... this leads us to remaking the whole SMCP set and that is a lot of work....
![image](https://user-images.githubusercontent.com/10247582/67862013-0144e000-fb2a-11e9-87da-f4359b8388ef.png)

... setting those proportions in tact was exactly that, what was needed to be decided upon, right after we generated the initial SMCP designs - remember my plead for reviewing the /o.smcp /h.smcp /b.smcp ?

**Comment by kateliev** [comment]
Ok, as I see it @servantb fixed /o.smcp. What about /h.smcp and all the glyphs that use the same horizontal stem width (:Blk - 440, :BlkRest - 430). Please confirm that this is also due to change, so i can start fixing the whole Cyrillic block - a this is a lot of work!
![image](https://user-images.githubusercontent.com/10247582/67934156-f47ac780-fbcf-11e9-8a15-dd6d4593e005.png)

**Comment by servantb** [comment]
After looking at these in context with all the other glyphs, and trying the /h.smcp crossbar at 440u, 430u, and 420, and in a variety of positions, I've determined that it doesn't much matter. It's aesthetic, and while my preference might be to move the crossbar of the /h.smcp down 10u, I wouldn't reduce the weight.

**Comment by kateliev** [comment]
Ok this seems settled then!
