### ISSUE TITLE
Glyphs to keep upright in italic

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#186]
Update list further.

See also discussion here:
https://typedrawers.com/discussion/3385/list-of-glyphs-that-remain-upright-in-italics/p1?new=1

**Comment by tphinney** [comment]
I am starting to rethink whether it is even worthwhile to keep anything upright in the oblique/italic, other than perhaps the /.notdef

This is not a text face, after all. And as the oblique/italic is largely automated in derivation, it would be VASTLY easier to just oblique and shift, and substitute out just a handful of alternates.

**Comment by tphinney** [comment]
@kateliev and @servantb I would love to get your take on this issue!

**Comment by kateliev** [comment]
@tphinney to be honest in my work I usually slant everything, except .notdef, my foundry logo and /estimate. Actually I always felt that this is the _normal thing to do_. After all italics should be derived from cursive writing and when you _write_ you usually keep everything (kind of) at the same angle...

But after you requested that _the python script_ should have exclusion list, containing glyphs that should not be slanted, you made me qestion my methods. I've done a little research and found out that it is _more common_ to have glyphs that are indeed not slanted. I also discovered that it is more practical to do so from type designers perspective - having to balance out a slanted multiply sign can loose you a couple of hours :).

As a conclusion I really do not know what to think - you infected me with the idea :) now i think that the _normal thing to do_ is to leave the math upright!

**Comment by kateliev** [comment]
I even slant .notdef - of course it largely depends on the design of it - but i consider it important because it should provide you with useful feedback that there is something missing. If i keep it the same between upright and italic, how would one know that some glyph failed in italic. For instance i might have a sentence with upright + italic mix and i would love to know what has gone wrong. Consider this example

... in terms of the Planck constant, _h_. The ... (all OK)
... in terms of the Planck constant, ? . The ... (glyph is missing)
... in terms of the Planck constant, _?_ . The ... (glyph is missing but indicating that is missing from different style)

**Comment by tphinney** [comment]
Huh, I would not have thought of that as a reason to slant the notdef. Interesting perspective.

Of course, having a generic notdef in the first place, not varying by weight/width, means you don’t know what font it is from without checking.

In any case, I am currently planning to not use the exceptions file, after all, and slant everything. Thanks for your feedback!
