### ISSUE TITLE
"M" in the /trademark symbol doesn't have contrast on the left stem in the :CtrEtc masters.

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#194]

**Comment by tphinney** [comment]
Good catch! I think I made the /trademark before I changed that in the /M design. I will fix it.

**Comment by tphinney** [comment]
fixed, also removed overlap

**Comment by kateliev** [comment]
Hah... I worked on that also. :) @tphinney I bet you have not pushed last night, because I saw it undone and fixed the issue. No worries - copying my version to a new glyph **/trademark.new** because I have fixed the above discussed issue + stem consistency (some stems going +1 in some masters) + width consistency across layers (:CtrEtc masters = non Ctr :Etc masters).

**Comment by tphinney** [comment]
Actually, we both fixed it.  :P  But I have put Vassil's version in the slot, he did a better version.
