### ISSUE TITLE
/bracketleft.case /bracketright.case may have baseline interaction issues

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#199]
Looks like their bottom horizontals don't stay below the baseline as perhaps they ought. Oops!

**Comment by servantb** [comment]
Not sure this will be any more of a problem than the top of the bracket. If anything, we have interaction issues between the /bracketleft and descenders (specifically the /j). This is solved easily enough with kerning. Or being used by a competent designer.

I don't think I'd worry about it. It's common enough not to even have .case versions of brackets, let alone worry about their interactions. (If I had a nickel for every j I've seen crash into a parenthesis...)

**Comment by tphinney** [comment]
Well, two options:
1) Do not have the base versions in the same kerning classes as their ".case" shifted alternates.
2) Adjust the designs so they don't interact with the baseline, so same kerning is an option.

**Comment by servantb** [comment]
Are the .case versions a requirement? If not, drop them. If so, option 1.

**Comment by kateliev** [comment]
@tphinney to be hones i see no problem here. I second @servantb that in the hands of competent designer this would not be a problem.

For me what is shown below is totally normal:
![image](https://user-images.githubusercontent.com/10247582/163408232-aa166238-f9a6-45f9-833e-065282b46bb5.png)

Just a side note about having a similar conversation with a renowned Bulgarian type designer/book illustrator - "If it collides, let is collide, it is understandable and expected to the eye of the beholder. Trying to avoid that will create even bigger aesthetical problem!" - discussing the large asymmetrical gap due to correcting problems like this using kerning... an example from a piece we did a while ago, where he pursued me to leave all collides unsolved (depside my panic attaks :) )
![image](https://user-images.githubusercontent.com/10247582/163409800-76a6e5ec-e285-49d0-a32a-fc0909efbe84.png)

**Comment by tphinney** [comment]
OK, I am willing to leave them alone. You two have persuaded me! @kateliev @servantb
