### ISSUE TITLE
Changes needed for Slant script

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#205]
A few tweaks needed to the Slant/Italic script, I think.

1) Maximum shift is 99, probably should go to three digits. Two digits was enough when we had a 1000-unit em square, but not with a 2000-unit em. I probably want to shift ~ 110, I think.

2) When I test it, it seems like my 99-unit shift is doubled! That seems like a bug. Although it could be a way of getting past 100....

3) Instead of processing "entire font except exclusion list" can we make it "selected glyphs less exclusion list"? This way we can use it later on specific glyphs, after changes are made to the upright. Or select a block of glyphs ...

4) Should we wipe sidebearing links for the slanted masters? I am thinking so.

**Comment by kateliev** [comment]
> Maximum shift is 99, probably should go to three digits. Two digits was enough when we had a 1000-unit em square, but not with a 2000-unit em. I probably want to shift ~ 110, I think.

Done: The spin-box now it accepts values from -1000 to 1000

> When I test it, it seems like my 99-unit shift is doubled! That seems like a bug. Although it could be a way of getting past 100....

Fixed: Was a bug, It looked like doubling but actually I was slating "at the origin" instead "in place"

> Instead of processing "entire font except exclusion list" can we make it "selected glyphs less exclusion list"? This way we can use it later on specific glyphs, after changes are made to the upright. Or select a block of glyphs ...

It depends... for now I am not going to solve that. It is more complicated than that... as when you run the script the following happens:
1. master table gets edited by adding the new masters
2. then layers needed are duplicated in all glyphs
3. and the new layers are transformed

... if you do that partially - on selected glyphs (or a block) - the others will be missing the newly created layers (at step (1) ). Then if you decide to run the script again to finish some other block, we must have to check (at step (1) ) if that master was added to the table and so on.... not that it is hard but might result total mayhem if done wrongly (by the user)...

There are other ways. Once we have the whole font with masters added and slanted - further tweaks could be done using Copy Layer Script (I might even add new combo button Copy To Italic Masters). Slanting can be done using TR Layer panel as shown below. Just select layers that you need to transform and hit the button.
![image](https://user-images.githubusercontent.com/10247582/68864591-1315ae00-06fa-11ea-96f5-5b1cc565b1f7.png)

I could even build us a new standalone tool to do exactly that, whatever you feel most usable - but i would suggest that we do not further complicate things for the "Build Italic Axis" script.

_I do not know what are you planning to work on after the font is slanted but see next comment..._

> Should we wipe sidebearing links for the slanted masters? I am thinking so.

NO! Will be mistake! 

If you had experienced any problems these are because we have glyphs bound to FIXED numbers. The logical bounds are perfectly fine and very usable!

But if you want to shift the newly slanted /H with -100u while its metrics are bound to =200u - no matter what you do, it will always jump back to its 200u LSB. So we better hunt down all those glyphs having numerical bindings and unbind them using TR Panel > Metrics> Unbind Metrics. Then it will work like charm. Tested it today - it is perfect! Having the font with all its metrics is a blessing!

**Comment by kateliev** [comment]
@tphinney this is the moment to discuss my new findings about the project. The resulting font occupies nearly 2Gb of memory and every operation adds unto information to i. Today i have hit Update font metrics at least 5 times (once per master) to update the accent positions which resulted a 4gb+ memory take from FL because it makes an undo snapshot of the entire font in memory (as it is global font action).... and of course the app became extremely laggy and unresponsive to a level that it is no longer usable. This is not a FL bug - this is us... so as far as I can predict... editing will be a nightmare! So there are two options - we either work very little and very carefully, or do what we do but use a lot less undo levels*... or we split the fonts in two and attempt to merge them when finished...

*There is a way to clear the memory from History panel > Forget History
![image](https://user-images.githubusercontent.com/10247582/68866464-2413ee80-06fd-11ea-83dc-b89ce423021a.png)

**Comment by tphinney** [comment]
I find FL takes about 3.5 GB initial RAM with the slanted font and its extra masters (from a base 0.8 GB or so). After that, doing something like "update metrics" consumes another .3 to .5 GB. I recently upgraded to 32 GB of RAM, so I could probably work with this without _too_ much trouble.

**Comment by kateliev** [comment]
> But I find the memory pattern ... odd.
Yes! but actually no mystery here - I just forgot to mention that after running the script if you feel fine with the results - delete the undo stack (forget history) - as during the transformation in the various stages (3) I update the font after each stage which causes undo information to be saved into memory. So three stages, three undo snapshots = 3 gb momory.

**Comment by tphinney** [comment]
Aha! OK, I get it now.

This shouldn't be a problem to work with at all, then. Not with my workflow, anyway.

I know you do more metrics updates, which generate big Undo caching. So I can see how this may be painful for you with the bigger font.  :(

**Comment by kateliev** [comment]
Closing this as most issues were discussed ans solved!
