### ISSUE TITLE
rename ".smcp" glyphs to ".sc"

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#220]
Need to rename .smcp glyphs to .sc extension instead

This will enable apps such as Glyphs to automatically compile them to _both_ smcp and c2sc features. Otherwise we would need to write c2sc code manually. Easier to fix the glyph names.

@kateliev if you feel like updating the font for this, I can do the spreadsheet and the .enc file. (Otherwise I will get to the font within the next day or two)

**Comment by kateliev** [comment]
@tphinney Will do - just to remind you that this benign looking task is actually very complicated:
- Changing glyph names form *.smcp -> *.sc
- Re-linking metrics referencing to *.smcp to *.sc
- Ensuring auto recipes are translated properly as there is no guarantee that FL will change those (why should it, if so - very smart of FL team to think of one such scenario)
- Ensuring that glyphs residing in metric classes are also properly renamed, if not the classes should be build anew.

**Comment by kateliev** [comment]
It is done:

1. Done via FL rename suffix, better use the APP then sorry
2. Done via scripting, because FL is not smart enough to change the recipes (should file a wish)
3. ....but FL is smart enough to update most recipes properly. Others done manually...
4. Glyphs in Classes were properly renamed. Class names were renamed by hand.
