### ISSUE TITLE
Improve static fonts

### ISSUE THREAD

**Issue by cssobral2013** [tphinney/science-gothic#226]

**Comment by tphinney** [comment]
Feedback is always welcome, but some kind of description of WHAT improvements you are seeking would sure be helpful!

I should clarify also that the static fonts are more a sort of side-effect or bonus option. They are an incredibly inefficient way to get the family out there, and involve a huge number of files. So it is not a focus of the project at all.

That said, anything we could relatively easily do I would consider. One thing that springs to mind: currently the static fonts are unhinted. We could certainly run them through TTFautohint.

**Comment by tphinney** [comment]
Then again, the main variable font is ALSO still unhinted. We’ve been hearing that autohinting was coming for variable fonts, but so far I gather it has still not arrived yet. :/

**Comment by cssobral2013** [comment]
@tphinney - It's time to think about legacy apps that don't support variable fonts.

**Comment by tphinney** [comment]
In what specific way? You still haven't answered my original question from January 6th.

Nonetheless, in an attempt to guess what you might mean:

Note that the full set of reasonable instances with this font is so large, I had to make different/distinct choices for the axis instances vs the predefined ones available in “dumb” apps that don’t expose sliders, etc.

The axis stops consist of  5 contrast (Y Opaque), 8 width, 9 weight, and 3 slant. That would be 1080 instances, if one had static fonts for them all. However, currently we only define 130 predefined instances in the variable font.

In my testing, I found that some legacy apps have trouble with more than 256 fonts in a family. I also found that more than 130-150 styles in a single family gets unwieldy in many common apps. This is why the predefined instances set is limited to 130 instead of allowing all 1080.

That is why we will be generating (and autohinting) static fonts just for those. It provides a wide variety of styles. In theory, we could split the static fonts into separate families in order to build a full set of 1080. That seems a bit crazy to me. Is that part of what you would want?

**Comment by cssobral2013** [comment]
@tphinney - It would be good if you just update static fonts to latest release, regardless of the number of weights.

**Comment by cssobral2013** [comment]
@tphinney - Okay then.

**Comment by kenmcd** [comment]
I started fixing the style groups so I can test the static fonts in LibreOffice.
And remembered this discussion/issue.
I can fix all the style groups so they work properly in LibreOffice (LO) and MS Word, etc.
Right now there are 130 different style groups. 
That is not gonna work in LO at all.

Also, as you mentioned above, having all 130 fonts in the same typographic family is unwieldy in many applications. 
For example in Affinity Publisher all those fonts are listed alphabetically which makes it quite the PITA to find the font you want in that long list.
Some apps like InDesign will sort the fonts by the weight and width settings inside the font to help users who are confronted with a crazy long list.
But many applications just list the fonts alphabetically.

Organizing by typographic family will change how the users will see the pre-defined instances when using the variable font
Same info, just grouped better (which is a good thing).
This will help users of the static fonts enormously.
And it will have no effect how the variable font operates.

I was already going to fix the style groups for testing and demos in LibreOffice anyway, 
and I was also going separate the fonts into 13 typographic families just for sanity sake.
Just that I need to do it in a separate file from the one I have been rummaging around inside of so I can create a clean pull request with just the name fixes.
So what do you think?

**Comment by tphinney** [comment]
IIRC the current Google fonts approach to this, I am going to trim the predefined instances to a much more minimal list of just the weight variations, and leave the large set for apps that handle the access by axis rather than long instance list.

This means that less savvy apps won’t see anything like the full range of instances. But then again, that full range is pretty overwhelming.

**Comment by tphinney** [comment]
Yes, this will be fixed as a side effect of #287 
Expecting to do this Very Soon Now
