### ISSUE TITLE
Some small caps have mismatched points /k.sc /x.sc

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#269]
There may be others, but @yarmola noticed these:
![image.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/b8f5be2d-b899-4365-9c89-242a184ef6db)

![image.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/983ba8c8-ad8a-489a-af07-bbc6b24deff0)

**Comment by kenmcd** [comment]
As an aspiring font maker I took a look at these.

The **x.sc** interpolation issue only requires a fix in one master.
**Cnd Ctr S** master
- x.sc does not have the startpoint at bottom left.
- the bottom of the stem is not horizontal (per Font Audit)

Fixed both of those and this interpolation issue is gone.
![x sc fixed](https://user-images.githubusercontent.com/844920/104111230-6a7ac400-5294-11eb-9118-8268af41e4ca.png)

The k.sc interpolation issue is a bit more complicated.
Many of the masters do not have the start point at the bottom left (it is at top left).
So setting all of those to bottom left made most of this issue go away.
But there is another issue with the upper right stem.
Around width 600 to 800 the stem is tapered rather than straight.
See image below (sorry do not know how to fix this one, yet).
Set those Variations settings and then move the Width and you will see the issue.
![k sc issue](https://user-images.githubusercontent.com/844920/104111316-5be0dc80-5295-11eb-8840-90ede1aaef3f.png)

I have been watching this project very closely to learn from some experts!

**Comment by tphinney** [comment]
These are both problems we have seen and erased many instances of. The first one is a minor dev error.

The second one is harder to fix. Basically, it is possible to have shapes that are perfectly good, but the interpolations have some distortions like this. One solution is to leave overlapping contours in the glyph. Doing that would make the shapes work beautifully, BUT some rasterization scenarios do not work as well with overlapping contours as one would like. So we generally try to avoid them. I am not sure it is possible in this case. I will have to see how we handled the upright K. My recollection is that I did the tweaks to fix it, but perhaps it was @kateliev

**Comment by kenmcd** [comment]
> I will have to see how we handled the upright K.

I looked at it, you added a looped corner.

**Comment by servantb** [comment]
I set all start points to lower left in k.sc and x.sc ✅
Also added looped connections to stem, arm, and leg in k.sc to correct interpolation kinks and splits.

**Comment by kateliev** [comment]
@tphinney this is now done. You could close the issue after build!
