### ISSUE TITLE
Angled cut on g j t f horizontals?

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#48]
In the original Bank Gothic, almost no purely horizontal strokes have an angled ending. There is none on E F L T or Z. The numerals however, do get angled endings, with the flag on the 5, and arguably the curved parts of 5 6 and 9.

Should we use, or avoid, angled cuts altogether on horizontal endings? I'm thinking of the g and j descenders, and the bottom of t.

(I am *not* suggesting angled endings for the "f" and "t" crossbars. That would be a bit much, I think.)

**Comment by servantb** [comment]
I tend to think of sans systems similarly to serifs. I think of the terminals in the uppercase as analogous to serifs, and the terminals in the lowercase become analogues to their serif cousins as well. In a serif font the terminals across things like a, c, s, f, t, j, y can have serifs, tapered terminals, and ball terminals in the same face and still feel cohesive. Sometimes these choices are backed up by the writing tool, and sometimes just tradition.

In the case of Science Gothic, I think the goal of coherency of the overall typeface is near the same level as the goal of legibility. First, the glyphs need to be referencing their platonic ideals. (They have to look like what they're supposed to look like.) Secondly, they should reference design elements in the other glyphs where possible, necessary, and functional.

My recommendations:
- Keep abrupt terminals on the t and f (functional, appropriate). 
- The y and j are justified in having an angled terminal, as they can echo the c (like the ball or teardrop terminal in a serif face).
- The g should probably have an abrupt terminal, as its cousins in other type styles would more often echo the lower portion of c or e than j or y (not so tapered as c or e, but not as flamboyant or mercurial as j or y).

**Comment by tphinney** [comment]
That all works for me. And yet...

"Keep the abrupt terminals on the t and f" I think makes 100% sense for the crossbars. But for the f ascender and the t foot/tail, which are analogous to the bottom of j and y, I think we should go angled.

**Comment by servantb** [comment]
I see what you're getting at. My head was stuck on the hooked f, which doesn't work in the Blk masters.

However, I also notice that the angle only happens on vertical strokes, and angle on the y and j are both a departure from that. I think it's admissible in the descenders, because they function as ancillaries to the visual rhythm of the text. They're below the main body, and don't disrupt the visual flow. Angles on the tail of the t and the ascender of the f on the other hand, would introduce angles that disrupt the visual rhythm along the x-axis. And I think it would be a bit much. I feel like the current design constraints give these glyphs plenty of visual interest without additional angles. (I may even argue agains angles on the j and y, but I feel they're excusable because of the unique space descenders occupy.)

**Comment by servantb** [comment]
Maybe we'll just have to fool around and see.

**Comment by tphinney** [comment]
I think of descenders and ascenders as ~ analogous.

And the angle *also* happens on the horizontal stroke of the 5. But it is weird because it is a heavy dominant stroke (in the usual font design rhythm) despite being horizontal. So maybe it has other reasons for being an exception.

**Comment by tphinney** [comment]
Yeah, let’s one of us give it a try: action item from this is to TEST (not necessarily check in) a version which has the angled cut on the _non-crossbar horizontals_ for these letters, g j t f. 
(g and j had them at one time before I backed them out, but I liked them better before.)

**Comment by tphinney** [comment]
Per chat, everybody likes the new version!
