### ISSUE TITLE
Check lowercase Contrast masters to make sure all thin strokes are 32u.

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#56]

**Comment by tphinney** [comment]
Brandon wrote: “I've noticed some of the Ctr lowercase have 36u or 40u instead of 32u (d, e, o). And s, strangely, has 30u. We'll have to go back through all these and make sure they're all 32u.”

I'm fixing the ones Brandon specifically identified. But there remains a task for a broader check across the font. Perhaps Igor's new guides will help?

**Comment by tphinney** [comment]
(My fix for d e o s was checked in)

**Comment by servantb** [comment]
Checked all lowercase latin glyphs, made changes and pushed.

Ctr: b, k, s, v, x, y
Blk Ctr: b, e, g, k, p, v, x, y
Cnd Ctr: k, v, x
Blk Cnd Ctr: b, e, g, k, p, q, v, y
Exp Ctr: b, e, k, v, x, y
Blk Exp Ctr: b, e, g, k, p, q, v, x, y

**Comment by tphinney** [comment]
I'm willing to assume this is good, and done.

**Comment by servantb** [comment]
I need to do one more sweep of the :Lt masters, which I'll do after @kateliev is done with the curvature changes.
