### ISSUE TITLE
Merging destroys linked element references 

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#87]
Current ways of merging the font repo unlink element references reused across multiple glyphs. 

This is the forth time I start rebuilding /uni0446 /uni0448 /uni0449 /uni0434 /uni0426 /uni0428 /uni0429 /uni0414

As you might suspect this is very time consuming...

**Comment by tphinney** [comment]
@kateliev Vassil, that sounds quite frustrating!

I have occasionally noted broken references as well, sometimes, with some of the diacritics.

We should attempt some experiments, so as to determine *exactly* what actions cause the element reference breakage. I am sure that it is related to cases where I either make a global change (like, something in Font Info), or I am changing a source glyph used by your glyphs (like /o or /m)... but for whatever seemingly good reason, I believe the problem happens when I _copy modified glyphs from your file, rather than starting with your file and adding my latest glyphs_.

But in some cases, I have modified things used in references, myself. With my work on diacritics, I have a lot of auto glyphs: both other diacritics (for example, grave from acute, or caron/háček from circumflex), and accented characters, which may themselves use an auto glyph as a component (example: /ccaron).

I *hope* that with slight workflow adjustments to how we do such merges, it will be possible to keep all references intact.

Suggestion:

1) In the future, each of us can only make changes by merging them (in FL) into the last checked-in master file. So whichever glyphs we edited, we are responsible for copying them into the last/freshest source file. And;

2)  If we want to make a global change, we not only do so in the last checked-in master file, but we do so quickly and expeditiously and check it right back in.

BUT, if the act of copying across fonts is causing the problem, which I suspect it is, I don’t immediately know what to do about it.

One of us ought to run some experiments to figure out, under what circumstances copying and pasting between copies of the font maintains element references (if any!), and under what circumstances it breaks them.

I am also wondering if named elements could help? I imagine that if there are no element names, FL may use an index or other internal tracking means. Naming elements might make this process work better?

**Comment by kateliev** [comment]
Actually I am not having problems with auto-layers nor with components (and/or Latin cross-references) but with **named-elements** that I use across the Cyrillic block. Every time I open the fresh repo file, **all the names are gone** and **elements are unlinked** - thus I have to start every day from scratch. 

For example naming the /Ц (Tse) leg. Then reusing it in /Щ (cyrShta) /Д (cyrDe) and etc., then replacing it in all the Glyphs, duplicating and flipping it where needed and so on... for all the designs across Cyrillic that reuse one another this is an hour or so repetitive work - just because FL's Replace element does not work on all layers (in contrast to Insert element). 

Yes I do believe this is a problem with manual copying glyphs font-to-font, as FL unlinks automatically upon copy -  a rather sane and welcome solution, but problematic for us. And finally as I have learned today the matter could be even more complicated. In fact not only naming the references is important, but the actual glyph order is also relevant. Thus if in my font version, recent glyphs no matter the named elements used, have different index than the ones in yours - links may be lost... so merging might also break the connections... a Catch 22 for elements I believe :)

As I think that the current workflow is good enough - we cannot avoid copy/pasting new glyphs - I will try to TypeRig a solution that allows me to rapidly name and replace elements. Maybe we could use this as a lesson to avoid using glyph-cross-linked elements for a while, until we find some sane solution...

**Comment by tphinney** [comment]
So, naming elements does not help, as you are already doing that? Bad news.

Also, I might have hoped that copying and pasting ALL the glyphs that use the same element(s) at once might solve the problem, but that has its own issues as one can only copy/paste blocks of glyphs, and have them replace existing ones, if are contiguous in the current view.

If you think you can work around the problem... ok. But let the rest of us know what—if anything—we can do to improve things? Also, if you have any ideas for how FontLab could do better with this?

@kateliev Should we "icebox" this issue for now?

**Comment by kateliev** [comment]
> So, naming elements does not help, as you are already doing that? Bad news.
Yes there is no other proper way to re-use elements across glyphs!

> Also, I might have hoped that copying and pasting ALL the glyphs that use the same element(s) at once might solve the problem, but that has its own issues as one can only copy/paste blocks of glyphs, and have them replace existing ones, if are contiguous in the current view.
_Paste Special> Paste by name_ might solve that problem, but it does not behave as i would expect it to - Just Paste special is kind of not working for me - Paste by name was a bliss in FL5

> If you think you can work around the problem... ok. But let the rest of us know what—if anything—we can do to improve things? Also, if you have any ideas for how FontLab could do better with this?
At least they could start with _Replace element that works on all layers, as well as naming elements on all layers simultaneously. At least that is what i would do in TypeRig.

> @kateliev Should we "icebox" this issue for now?
Yes i am closing this ... for now...
