### ISSUE TITLE
/acutecomb.case /gravecomb.case /uni0302.case /uni0304.case /uni030A.case (circumflex, macron, ring)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#88]
.case alternates for previously made diacritics

**Comment by servantb** [comment]
I think the weight of all these looks good. I would argue about position of the /uni030A.case above the A (which I understand is potentially a new issue). If this design is the one we want to go with for the /uni030A.case (ring), which I believe it is, then the ring needs to be positioned higher above the A, in line with the other diacritics. Otherwise it requires a new (larger) design for the :Blk, :BlkCnd, and :BlkExp masters at the least, and potentially all masters at most.

Diacritics.typo.cz notes, "The ring is sometimes merged with upper case Å, but Scandinavian users have complained about this practice."

This recommendation is enough to convince me the ring should not be attached to the top of the A. I think it would look better floating.

**Comment by tphinney** [comment]
It's now floating, as of tonight. Take a look in the morning?

**Comment by servantb** [comment]
Looks much better floating. Noticed an anchor off visual center on the /A :BlkCtr (fixed).
The other .case diacritics look great.
I'm reconsidering the ring.case, but we'll track that in issue #78
