### ISSUE TITLE
Create UFO + FontMake workflow

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#91]
Does Google require that we be able to generate final variable fonts through UFO + FontMake? I believe so, but will double check.

**Comment by davelab6** [comment]
Yes, and the sooner the better so there isn't a crunch of font engineering at the end; it would be ideal to have a travis or other CI system set up to build the fonts from sources with fontmake on each commit to master :)

**Comment by tphinney** [comment]
Note: CI = “Continuous Integration”

**Comment by tphinney** [comment]
Changed title to reflect understanding. This is now an implementation task....

1) What do we need besides UFO files and a designspace file, as inputs to the build process?
2) Will FontMake cope in a desirable way with things like some glyphs not present for all masters? Or glyphs present but incompatible? (Hoping it just drops such glyphs, in both cases, when building a variable TTF.)
3) Is current FontLab UFO export OK for our needs? Will require testing.
4) If not, we will need some scripting so as to automate the UFO export from FontLab

**Comment by tphinney** [comment]
Vassil has been working on this, making progress. We will use a FontLab Python script that will process a working file to make it ready to export UFO that will not cause trouble with FontMake:
- we often have non-compatible-for-variations glyphs-in-development in the current working file. I was removing these manually already. The script will ID and delete these.
- For now, the script will deal with glyphs that mix elements and components by  just flattening the entire font (which eliminates components). We may be able to avoid this, by changing those glyphs upstream.

There are still a couple of unsolved problems, so it is not done yet. But coming along.

**Comment by kateliev** [comment]
First things first - it is done!

**Now some answers:**

> What do we need besides UFO files and a designspace file, as inputs to the build process?
Nothing more!

> Will FontMake cope in a desirable way with things like some glyphs not present for all masters? Or glyphs present but incompatible? (Hoping it just drops such glyphs, in both cases, when building a variable TTF.)

Nope - it is unforgiving! Will not drop glyphs with missing masters or incompatible glyphs. We have to clean up the mess ourselves! _See below..._

> Is current FontLab UFO export OK for our needs? Will require testing.
Yes it is perfectly fine with minor exceptions.  _See below..._

> If not, we will need some scripting so as to automate the UFO export from FontLab
For now we do not need any external command line scripts to prepare UFO-s for FontMake. Dough we need some internal scripting to sort out the problems we created ourselves. _See below..._

**What we did wrong and how to fix it (case study):**
- incompatible glyphs - are expected in any design process - we have suprisingly quite few of those. They need to be made compatible or deleted. Currently I have prepared a script to locate and delete the most obvious cases;
![image](https://user-images.githubusercontent.com/10247582/65148827-9633c400-da29-11e9-9f7c-b428387634f3.png)
- glyphs with overlaping or self-intersecting contours - are also part of the design process. As long as they are compatible they are perfectly fine. I do not advise jumping into _remove overlap_ at this design stage as there are still a lot to be changed and desired design-wise. So for now I suggest running _fontmake_ with  **--keep-overlaps** attribute - works perfectly fine and is OK for testing purposes at least if you ask me!
![image](https://user-images.githubusercontent.com/10247582/65147453-d80f3b00-da26-11e9-9f25-af77cde95828.png)
![image](https://user-images.githubusercontent.com/10247582/65147420-c62d9800-da26-11e9-8a0e-8f94630a5bbf.png)
- glyphs with "mixed" references - we have some of these very strange designer decisions where Components are present on some layers, but Referenced shapes are residing on others. Fontlab will report the glyph as compatible, because in fact it uses the same contour, but with different reference. As expected this is totally not acceptable for fontmake and will result an error.  Here for example is an /Eth glyph:
![image](https://user-images.githubusercontent.com/10247582/65147922-c4180900-da27-11e9-854d-34d56dd13960.png)
![image](https://user-images.githubusercontent.com/10247582/65147963-e0b44100-da27-11e9-833f-672e884feccb.png)

- glyphs with messy/wrong tags - we all use tags to mark our work as we progress trough the project, but sometimes a typo occurs. Currently we have glyphs that have "white space" as a valid tag. This can be seen in the _"Classes panel" > "Tags"_ sub-menu. For me this is a FL bug. So _Features Panel > Hamburger menu > Include Classes > Tags_ should be turned off! Needless to say what happens when non-unicode, meaningless name (as '') lands in the OT code - mayhem begins. I have added subroutine in the script discussed to locate and clean those tags.
![image](https://user-images.githubusercontent.com/10247582/65148174-54eee480-da28-11e9-94a5-ef0d9e8da639.png)
![image](https://user-images.githubusercontent.com/10247582/65148495-fd9d4400-da28-11e9-8d00-d58bf02b1ed7.png)
![image](https://user-images.githubusercontent.com/10247582/65149896-a3ea4900-da2b-11e9-8001-14a5b842aa75.png)

- [mark] and [mkmk] features - these are a real pain. Regardless of the export profile setting -  "generate..." or "do not generate..." fontmake will want that feature present because of the anchors present. So it will always return 'Base master not found.', 'MarkBasePos'....
![image](https://user-images.githubusercontent.com/10247582/65148969-e7dc4e80-da29-11e9-814d-f11cdc80c3bf.png)
![image](https://user-images.githubusercontent.com/10247582/65149161-49042200-da2a-11e9-8481-28c7cdffa031.png)

**Comment by kateliev** [comment]
So with all that noted.
**UFO+Designspace+FontMake workflow:**
1. Prepare your custom export profile based on _UFO+Designspace_;
2. Run* _SG-UFO-Prepare.py_ that is in the scripts folder within FL;
3. Check if _Features Panel > Hamburger > Include Classes > Tags_ is turned off;
4. Delete any [mark] and [mkmk] features from the _Features Panel_ and then recreate them;
5. Export your UFO+Designspace
6. Run fontmake into the respected folder using:
`fontmake -m .\ScienceGothic-3a-18m.designspace -o variable --keep-overlaps  `

----
* Running the script will not always clean up every broken glyph. For instance /zero.zero is the ultimate evil. It is compatible and is not with mixed reference, nevertheless fontmake will result an error. So if you encounter cases like this, just delete or fix the incompatible characters, no matter FL claims the opposite.

**Comment by tphinney** [comment]
@kateliev What needs to be customized in the custom export profile in FL?

**Comment by tphinney** [comment]
Also: keeping overlap will be necessary through to the end, for some glyphs at least.

In general, careful attention to consistent path direction will ensure good results from the overlap. I use counter-clockwise paths for filled contours, PostScript-style, since we are drawing with PS style outlines.

With exporting directly from FontLab, I assume we are getting the FL conversion from PS to TTF. In this FontMake workflow, when is the conversion to TT outlines happening? Is that part of the output profile from FL > UFO?

**Comment by kateliev** [comment]
> Also: keeping overlap will be necessary through to the end, for some glyphs at least.
I am OK with that, as long as it does not mess with hinting...

> In general, careful attention to consistent path direction will ensure good results from the overlap. I use counter-clockwise paths for filled contours, PostScript-style, since we are drawing with PS style outlines.
Yes this is the general rule of the thumb, but... it will be better for us to remove overlaps and fix the glyphs one-by-one while we work, because there will be cases where remove overlap will make the layers incompatible as seen in the straight-to-soft corners we use now.

> With exporting directly from FontLab, I assume we are getting the FL conversion from PS to TTF. In this FontMake workflow, when is the conversion to TT outlines happening?

TT Conversion is left to FontMake at build time. Yes we could force FL to output TT flavored UFO and use that instead, but my opinion is to keep the UFO as close to the source as possible... And yes i know that FL excels in all things Bezier, so FLs conversion is seriously better than any current tool, but the nature of the project is not that pretentious (IMHO). 

>  Is that part of the output profile from FL > UFO?
Yes there is an option to convert to TT in the profiles, but currently I am not using it. I am providing FontMake with clean-close-to-the-original source and let it handle all the transformations needed - PS to TT, Components decomposition, Remove overlap, Master matching (if needed), Contour optimization, Auto-hinting and etc.

**Comment by kateliev** [comment]
> What needs to be customized in the custom export profile in FL?

Actually nothing. But it is a good practice to duplicate the stock profile and customize it in some way. For this case study I used (and advise to do so in future) the following (annotated):
* curve type - PS - I definitely want a UFO 1:1 to what we have in FL
* remove overlaps and contour optimization - turned off so that the masters stay unchanged (1:1 to original)
* hinting - turned off because I prefer that fontmake auto-hints the resulting files. Also that speeds up the export as it is slow enough already
* OT features - all set to defaults - I prefer that FL generates the features

**Comment by tphinney** [comment]
Now I have this running (as well as Vassil).

NOTE one difference in my new custom export profile, which I am using after tonight's UFO export: curve type TT. Dave was clear that he wants the UFO source in TT. Heck, he'd probably prefer us to work in native TT in FontLab. Plus, I believe that FontLab's TT conversion is preferable to FontMake’s conversion. So, I am doing this at UFO export time going forward. (After the build I just did.)

**Comment by tphinney** [comment]
As discussed elsewhere later, we do indeed need to remove overlap where possible. It can affect screen rendering, on glyph edges and/or at small sizes.
